build:
  cuda_version: "12.1.1"
  python_packages:
    - "torch==2.1.1"
    - "einops==0.6.1"
    - "transformers>=4.32.0"
    - "auto-gptq==0.6.0"
    - "optimum>=1.12.0"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.27.1"
